# Generated by Django 5.0.14 on 2026-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, choices=[('DLP', 'DLP'), ('Email', 'Email'), ('OT', 'OT'), ('Proxy', 'Proxy'), ('UEBA', 'UEBA'), ('ThreatIntelligence', 'TI'), ('IAM', 'IAM'), ('EDR', 'EDR'), ('NDR', 'NDR'), ('Cloud', 'Cloud'), ('SIEM', 'SIEM'), ('WAF', 'WAF'), ('Other', 'Other')], default='', help_text='Case category (案件类别)', max_length=30),
        ),
    ]
