AI_SCHEMA_KEY = "ai"
AI_PROFILE_INVESTIGATION = "investigation"
AI_PROFILE_MCP = "mcp"
AI_PROFILE_VERSION = "2026-06-20"

AI_FIELD_PROFILES = {
    "cases.Case": {
        AI_PROFILE_INVESTIGATION: [
            "created_at",
            "updated_at",
            "title",
            "severity",
            "impact",
            "priority",
            "confidence",
            "description",
            "category",
            "tags",
            "status",
            "acknowledged_time",
            "assignee",
            "closed_time",
            "verdict",
            "summary",
            "alerts",
            "enrichments",
            "comments",
            "audit_logs",
        ],
        AI_PROFILE_MCP: [
            "id",
            "case_id",
            "created_at",
            "updated_at",
            "title",
            "severity",
            "impact",
            "priority",
            "confidence",
            "description",
            "category",
            "tags",
            "correlation_uid",
            "status",
            "assignee",
            "closed_time",
            "verdict",
            "summary",
            "alerts",
            "enrichments",
        ],
    },
    "alerts.Alert": {
        AI_PROFILE_INVESTIGATION: [
            "created_at",
            "updated_at",
            "title",
            "severity",
            "confidence",
            "impact",
            "disposition",
            "action",
            "labels",
            "desc",
            "first_seen_time",
            "last_seen_time",
            "rule_id",
            "rule_name",
            "analytic_name",
            "analytic_type",
            "analytic_state",
            "analytic_desc",
            "product_category",
            "product_vendor",
            "product_name",
            "product_feature",
            "policy_name",
            "policy_type",
            "policy_desc",
            "risk_level",
            "status",
            "status_detail",
            "artifacts",
            "enrichments",
        ],
        AI_PROFILE_MCP: [
            "id",
            "alert_id",
            "created_at",
            "updated_at",
            "title",
            "severity",
            "confidence",
            "impact",
            "disposition",
            "action",
            "labels",
            "desc",
            "first_seen_time",
            "last_seen_time",
            "rule_id",
            "rule_name",
            "correlation_uid",
            "src_url",
            "source_uid",
            "data_sources",
            "analytic_name",
            "analytic_type",
            "analytic_state",
            "analytic_desc",
            "tactic",
            "technique",
            "sub_technique",
            "mitigation",
            "product_category",
            "product_vendor",
            "product_name",
            "product_feature",
            "policy_name",
            "policy_type",
            "policy_desc",
            "risk_level",
            "status",
            "status_detail",
            "remediation",
            "artifacts",
            "enrichments",
        ],
    },
    "artifacts.Artifact": {
        AI_PROFILE_INVESTIGATION: [
            "created_at",
            "updated_at",
            "name",
            "type",
            "role",
            "value",
            "enrichments",
        ],
        AI_PROFILE_MCP: [
            "id",
            "artifact_id",
            "created_at",
            "updated_at",
            "name",
            "type",
            "role",
            "value",
            "enrichments",
        ],
    },
    "enrichments.Enrichment": {
        AI_PROFILE_INVESTIGATION: [
            "created_at",
            "updated_at",
            "name",
            "type",
            "provider",
            "value",
            "desc",
        ],
        AI_PROFILE_MCP: [
            "id",
            "enrichment_id",
            "created_at",
            "updated_at",
            "name",
            "type",
            "provider",
            "value",
            "desc",
        ],
    },
    "knowledge.Knowledge": {
        AI_PROFILE_MCP: [
            "id",
            "knowledge_id",
            "created_at",
            "updated_at",
            "title",
            "body",
            "expires_at",
            "source",
            "tags",
        ],
    },
}


def get_profile_fields(model_label, profile):
    model_profiles = AI_FIELD_PROFILES[model_label]
    return tuple(model_profiles[profile])
