# Generated by Django 6.0.6 on 2026-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='tactic',
            field=models.CharField(blank=True, choices=[('Reconnaissance', 'Reconnaissance'), ('Resource Development', 'Resource Development'), ('Initial Access', 'Initial Access'), ('Execution', 'Execution'), ('Persistence', 'Persistence'), ('Privilege Escalation', 'Privilege Escalation'), ('Defense Evasion', 'Defense Evasion'), ('Credential Access', 'Credential Access'), ('Discovery', 'Discovery'), ('Lateral Movement', 'Lateral Movement'), ('Collection', 'Collection'), ('Command and Control', 'Command and Control'), ('Exfiltration', 'Exfiltration'), ('Impact', 'Impact')], default='', help_text='Mapped MITRE tactic (映射的 MITRE 战术)', max_length=100),
        ),
    ]
