# Generated by Django 5.0.14 on 2026-06-15

import uuid

from django.db import migrations, models


def populate_access_keys(apps, schema_editor):
    Attachment = apps.get_model("attachments", "Attachment")
    for attachment in Attachment.objects.filter(access_key__isnull=True):
        attachment.access_key = uuid.uuid4()
        attachment.save(update_fields=["access_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="access_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_access_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attachment",
            name="access_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
