# Generated by Django 5.0.14 on 2026-06-21 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='case',
            field=models.OneToOneField(blank=True, help_text='Case this Knowledge was extracted from; empty for manual Knowledge (知识提取来源 Case, 手动知识为空)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_knowledge', to='cases.case'),
        ),
    ]
