# Generated by Django 5.0.14 on 2026-06-17 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


def migrate_user_auth_type_and_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("auth", "Group")
    user_group, _ = Group.objects.get_or_create(name="user")
    Group.objects.get_or_create(name="viewer")

    admin_group = Group.objects.filter(name="admin").first()
    if admin_group:
        User.objects.filter(groups=admin_group).update(is_superuser=True)

    for user in User.objects.all():
        user.auth_type = "ldap" if getattr(user, "ldap_dn", "") else "local"
        user.save(update_fields=["auth_type"])
        if not user.is_superuser and not user.groups.filter(name__in=["user", "viewer"]).exists():
            user.groups.add(user_group)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('local', 'Local Password'), ('ldap', 'LDAP')], default='local', max_length=20),
        ),
        migrations.RunPython(migrate_user_auth_type_and_roles, noop),
        migrations.RemoveField(
            model_name='user',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ldap_dn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=apps.accounts.models.generate_api_key, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
