# Generated by Django 5.0.14 on 2026-06-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_avatar_user_avatar_content_type_and_more'),
        ('attachments', '0002_attachment_access_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_content_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_users', to='attachments.attachment'),
        ),
    ]
