# Generated by Django 5.0.14 on 2026-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_avatar_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_case_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_playbook_completion',
            field=models.BooleanField(default=True),
        ),
    ]
