# Generated by Django 5.0.14 on 2026-06-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachment_access_key'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('resource_key', models.CharField(blank=True, default='', max_length=50)),
                ('resource_label', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='inbox_messages', to='attachments.attachment')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inbox.inboxmessage')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inbox_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inbox_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_states', to='inbox.inboxmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_recipient_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inbox_message_recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='recipients',
            field=models.ManyToManyField(related_name='inbox_messages', through='inbox.InboxMessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inboxmessagerecipient',
            index=models.Index(fields=['user', 'read_at'], name='inbox_messa_user_id_a3c440_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxmessagerecipient',
            index=models.Index(fields=['user', 'created_at'], name='inbox_messa_user_id_012503_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inboxmessagerecipient',
            unique_together={('message', 'user')},
        ),
    ]
