# Generated by Django 5.0.14 on 2026-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inboxmessage',
            index=models.Index(fields=['-created_at', '-id'], name='inbox_message_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxmessagerecipient',
            index=models.Index(fields=['user', 'read_at', 'message'], name='inbox_rec_user_read_msg_idx'),
        ),
    ]
