# Generated by Django 5.0.14 on 2026-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', '-created_at', '-id'], name='comment_obj_time_idx'),
        ),
    ]
