# Generated by Django 5.0.14 on 2026-06-24 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('model', models.CharField(max_length=200)),
                ('api_key', models.TextField(blank=True, default='')),
                ('proxy', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_llm_provider_configs',
                'ordering': ['priority', 'name', 'created_at'],
            },
        ),
    ]
