# Generated by Django 5.0.14 on 2026-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelAlienVaultOTXConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(default='https://otx.alienvault.com/api/v1', max_length=500)),
                ('proxy', models.CharField(blank=True, default='', max_length=500)),
                ('timeout_seconds', models.FloatField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_ti_alienvault_otx_config',
            },
        ),
    ]
