# Generated by Django 5.0.14 on 2026-06-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_threatintelalienvaultotxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiemElkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('host', models.URLField(blank=True, default='', max_length=500)),
                ('api_key', models.TextField(blank=True, default='')),
                ('verify_certs', models.BooleanField(default=False)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('action_index', models.CharField(default='siem-alert', max_length=255)),
                ('action_poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_siem_elk_config',
            },
        ),
        migrations.CreateModel(
            name='SiemSplunkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=8089)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.TextField(blank=True, default='')),
                ('scheme', models.CharField(default='https', max_length=10)),
                ('verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_siem_splunk_config',
            },
        ),
    ]
