# Generated by Django 5.0.14 on 2026-06-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_siemelkconfig_siemsplunkconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siemelkconfig',
            name='process_alert_from_index_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siemelkconfig',
            name='action_index',
            field=models.CharField(blank=True, default='siem-alert', max_length=255),
        ),
    ]
