# Generated by Django 5.0.14 on 2026-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_siemelkconfig_process_alert_from_index_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siemelkconfig',
            name='action_size',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
