# Generated by Django 5.0.14 on 2026-06-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_siemelkconfig_action_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('server_uri', models.CharField(blank=True, default='', max_length=500)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('bind_dn', models.CharField(blank=True, default='', max_length=500)),
                ('bind_password', models.TextField(blank=True, default='')),
                ('user_search_base_dn', models.CharField(blank=True, default='', max_length=500)),
                ('user_login_attr', models.CharField(default='uid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_ldap_config',
            },
        ),
    ]
