# Generated by Django 5.0.14 on 2026-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_ldapconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('prompt_language', models.CharField(default='en', max_length=10)),
                ('module_consumer_group', models.CharField(default='agentic-modules', max_length=255)),
                ('module_block_ms', models.PositiveIntegerField(default=1000)),
                ('module_stream_maxlen', models.PositiveIntegerField(default=10000)),
                ('webhook_stream_maxlen', models.PositiveIntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_agentic_runtime_config',
            },
        ),
    ]
