# Generated by Django 5.0.14 on 2026-06-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_agenticruntimeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenticruntimeconfig',
            name='module_consumer_group',
        ),
    ]
