# Generated by Django 5.0.14 on 2026-06-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_agenticruntimeconfig_module_consumer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenticruntimeconfig',
            name='module_block_ms',
        ),
    ]
