# Generated by Django 6.0.6 on 2026-06-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_unify_agentic_runtime_stream_maxlen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenticruntimeconfig',
            table='setting_agentic_runtime_config',
        ),
        migrations.AlterModelTable(
            name='ldapconfig',
            table='setting_ldap_config',
        ),
        migrations.AlterModelTable(
            name='llmproviderconfig',
            table='setting_llm_provider_configs',
        ),
        migrations.AlterModelTable(
            name='siemelkconfig',
            table='setting_siem_elk_config',
        ),
        migrations.AlterModelTable(
            name='siemsplunkconfig',
            table='setting_siem_splunk_config',
        ),
        migrations.AlterModelTable(
            name='threatintelalienvaultotxconfig',
            table='setting_ti_alienvault_otx_config',
        ),
    ]
